import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags as t } from "@lezer/highlight";

/**
 * צבעי PHP Dark+ (Cursor theme-defaults) להדגשת תחביר —
 * משותף ליוד ולשפות נוספות (JS/PHP/HTML/CSS/SQL…).
 */
export const yodPhpDarkColors = {
  background: "#1E1E1E",
  foreground: "#D4D4D4",
  comment: "#6A9955",
  string: "#CE9178",
  number: "#B5CEA8",
  control: "#C586C0",
  keyword: "#569CD6",
  function: "#DCDCAA",
  variable: "#9CDCFE",
  className: "#4EC9B0",
  operator: "#D4D4D4",
  lineNumber: "#858585",
  tag: "#569CD6",
  attribute: "#9CDCFE",
  meta: "#D4D4D4",
  regexp: "#D16969",
  heading: "#569CD6",
  link: "#CE9178",
  invalid: "#f44747",
} as const;

export const yodHighlightStyle = HighlightStyle.define([
  { tag: t.comment, color: yodPhpDarkColors.comment, fontStyle: "italic" },
  { tag: t.lineComment, color: yodPhpDarkColors.comment, fontStyle: "italic" },
  { tag: t.blockComment, color: yodPhpDarkColors.comment, fontStyle: "italic" },
  { tag: t.docComment, color: yodPhpDarkColors.comment, fontStyle: "italic" },
  { tag: t.string, color: yodPhpDarkColors.string },
  { tag: t.special(t.string), color: yodPhpDarkColors.string },
  { tag: t.character, color: yodPhpDarkColors.string },
  { tag: t.number, color: yodPhpDarkColors.number },
  { tag: t.integer, color: yodPhpDarkColors.number },
  { tag: t.float, color: yodPhpDarkColors.number },
  { tag: t.bool, color: yodPhpDarkColors.keyword },
  { tag: t.null, color: yodPhpDarkColors.keyword },
  { tag: t.atom, color: yodPhpDarkColors.keyword },
  { tag: t.unit, color: yodPhpDarkColors.number },
  { tag: t.controlKeyword, color: yodPhpDarkColors.control },
  { tag: t.keyword, color: yodPhpDarkColors.keyword },
  { tag: t.modifier, color: yodPhpDarkColors.keyword },
  { tag: t.definitionKeyword, color: yodPhpDarkColors.keyword },
  { tag: t.moduleKeyword, color: yodPhpDarkColors.keyword },
  { tag: t.operatorKeyword, color: yodPhpDarkColors.control },
  { tag: t.function(t.variableName), color: yodPhpDarkColors.function },
  { tag: t.function(t.definition(t.variableName)), color: yodPhpDarkColors.function },
  { tag: t.definition(t.function(t.variableName)), color: yodPhpDarkColors.function },
  { tag: t.variableName, color: yodPhpDarkColors.variable },
  { tag: t.definition(t.variableName), color: yodPhpDarkColors.variable },
  { tag: t.propertyName, color: yodPhpDarkColors.variable },
  { tag: t.attributeName, color: yodPhpDarkColors.attribute },
  { tag: t.attributeValue, color: yodPhpDarkColors.string },
  { tag: t.className, color: yodPhpDarkColors.className },
  { tag: t.typeName, color: yodPhpDarkColors.className },
  { tag: t.namespace, color: yodPhpDarkColors.className },
  { tag: t.labelName, color: yodPhpDarkColors.variable },
  { tag: t.tagName, color: yodPhpDarkColors.tag },
  { tag: t.angleBracket, color: yodPhpDarkColors.operator },
  { tag: t.operator, color: yodPhpDarkColors.operator },
  { tag: t.punctuation, color: yodPhpDarkColors.operator },
  { tag: t.bracket, color: yodPhpDarkColors.operator },
  { tag: t.brace, color: yodPhpDarkColors.operator },
  { tag: t.paren, color: yodPhpDarkColors.operator },
  { tag: t.squareBracket, color: yodPhpDarkColors.operator },
  { tag: t.separator, color: yodPhpDarkColors.operator },
  { tag: t.meta, color: yodPhpDarkColors.meta },
  { tag: t.processingInstruction, color: yodPhpDarkColors.meta },
  { tag: t.regexp, color: yodPhpDarkColors.regexp },
  { tag: t.escape, color: yodPhpDarkColors.string },
  { tag: t.color, color: yodPhpDarkColors.number },
  { tag: t.heading, color: yodPhpDarkColors.heading, fontWeight: "bold" },
  { tag: t.heading1, color: yodPhpDarkColors.heading, fontWeight: "bold" },
  { tag: t.heading2, color: yodPhpDarkColors.heading, fontWeight: "bold" },
  { tag: t.heading3, color: yodPhpDarkColors.heading, fontWeight: "bold" },
  { tag: t.link, color: yodPhpDarkColors.link },
  { tag: t.url, color: yodPhpDarkColors.link },
  { tag: t.emphasis, fontStyle: "italic" },
  { tag: t.strong, fontWeight: "bold" },
  { tag: t.strikethrough, textDecoration: "line-through" },
  { tag: t.monospace, color: yodPhpDarkColors.foreground },
  { tag: t.invalid, color: yodPhpDarkColors.invalid },
  { tag: t.name, color: yodPhpDarkColors.foreground },
  { tag: t.literal, color: yodPhpDarkColors.string },
  { tag: t.self, color: yodPhpDarkColors.keyword },
]);

export const yodSyntaxHighlighting = syntaxHighlighting(yodHighlightStyle);
